version: '3'
services:
  nginx:
    links: 
      - bioticexplorer
      - notebook
    image: nginx:latest
    restart: always
    container_name: reverse_proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  bioticexplorer:
    image: iambaim/bioticexplorer:latest
    restart: always
    depends_on:
      - dbserver
    volumes:
      - bio_db_data:/data
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    expose:
      - 8080

  rstudio:
    image: rocker/geospatial:latest
    restart: always
    depends_on:
      - dbserver
    environment:
      - DISABLE_AUTH=true
    volumes:
      - work_data:/home/rstudio/work
    expose:
      - 8787

  notebook:
    image: jupyter/r-notebook:latest
    restart: always
    depends_on:
      - dbserver
    volumes:
      - ./conf/jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py
      - work_data:/home/jovyan/work
    expose:
      - 8888
    command: start.sh jupyter lab --LabApp.token=''

  dbserver:
    image: monetdb/monetdb:latest
    restart: always
    volumes:
      - bio_db_data:/data
      - bio_db_data:/var/monetdb5/dbfarm
    expose:
      - 50000
    ports:
      - 50000:50000

volumes:
    bio_db_data:
    work_data:
