name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get commit hash
        run: |
          echo "GIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        shell: bash
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            iambaim/bioticexplorer:latest
            iambaim/bioticexplorer:${{ env.GIT_SHA }}
      -
        name: Make tag
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: BioticExplorer Docker-${{ env.GIT_SHA }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
